#!/bin/bash
# DocPad daemon
# chkconfig: 345 20 80
# description: Manages the docpad-server instance
# processname: docpad-server

DAEMON_PATH="/home/komodo-website/qa"

DAEMON="./node_modules/docpad/bin/docpad-server"

NAME="docpad-server"
PIDFILE="$DAEMON_PATH/$NAME.pid"
LOGFILE="$DAEMON_PATH/$NAME.log"

ENVIRONMENT="qa"
HOME="/home/komodo-website"

USER="nathanr"

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    cd $DAEMON_PATH

    PID=$(su $USER -c "source ~/.nvm/nvm.sh && export DOCPAD_ENV=$ENVIRONMENT && export HOME=$HOME && $DAEMON > $LOGFILE & echo \$! ")

    if [ -z $PID ]; then
        printf "%s\n" "Fail"
    else
        echo $PID > $PIDFILE
        printf "%s\n" "Ok"
    fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
